
- name: Local setup for quickstart
  hosts: localhost
  connection: local
  tasks:
    - name: Host setup
      shell: >
        sudo hostnamectl set-hostname undercloud;
        echo 'undercloud' | sudo dd of=/etc/hostname;
        echo "127.0.0.1 $(hostname) $(hostname).openstacklocal" | sudo tee -a /etc/hosts;
        echo "127.0.0.2 undercloud undercloud.openstacklocal" | sudo tee -a /etc/hosts;
        if [ ! -e ${HOME}/.ssh/id_rsa.pub ] ; then
            if [[ -e ${HOME}/.ssh/id_rsa ]]; then
                ssh-keygen -y -f ${HOME}/.ssh/id_rsa > ${HOME}/.ssh/id_rsa.pub;
            else
                ssh-keygen -N "" -f ${HOME}/.ssh/id_rsa;
            fi
        fi;
        cat ~/.ssh/id_rsa.pub | sudo tee -a /root/.ssh/authorized_keys | tee -a ~/.ssh/authorized_keys;

        sudo yum remove -y puppet hiera puppetlabs-release rdo-release;
        sudo rm -rf /etc/puppet /etc/hiera.yaml;
        sudo cp {{tripleo_root}}/tripleo-ci/test-environments/overcloud-cacert.pem /etc/pki/ca-trust/source/anchors/;
        sudo update-ca-trust extract;
        cp -f {{ lookup('env', 'TE_DATAFILE') }} ~/instackenv.json;

    - name: Delete /tmp/eth2.cfg file
      file: dest=/tmp/eth2.cfg state=absent

    - name: Create /tmp/eth2.cfg file
      blockinfile:
        dest: /tmp/eth2.cfg
        content: |
          network_config:
            - type: interface
              name: eth2
              use_dhcp: false
              addresses:
                - ip_netmask: 10.0.0.1/24
                - ip_netmask: 2001:db8:fd00:1000::1/64
        create: yes

    - name: Add eth2 interface from /tmp/eth2.cfg
      command: os-net-config -c /tmp/eth2.cfg -v
      become: true
      when: network_isolation|bool

    - name: Remove redundant hosts from instackenv.json
      shell: >
        cp ~/instackenv.json ~/instackenv.json.backup;
        cat ~/instackenv.json | jq '{"nodes": .nodes[:{{ lookup('env', 'NODECOUNT') }}]}' > /tmp/instackenv1.json &&
        mv /tmp/instackenv1.json ~/instackenv.json;

    - name: Install ipmitool if not installed
      yum: name=ipmitool state=latest
      become: true

    - name: Set user permissions for ~/.cache for building images
      shell: sudo chown -R $USER ~/.cache || true
