---
- name: Prepare environment for quickstart
  hosts: undercloud
  gather_facts: no
  tasks:
    - name: Remove old puppet and hiera
      file: path='{{ item }}' state=absent
      with_items:
        - /etc/puppet
        - /etc/hiera.yaml
    - name:
      yum: name='{{ item }}' state=absent
      with_items:
        - puppet
        - hiera
        - puppetlabs-release
        - rdo-release
    - name: Install python-tripleoclient
      yum: name=python-tripleoclient state=latest
#    - name: Repository setup
#      block:
#        - name: Clean
#          shell: yum clean all
#          become: true
#
#        - name: Remove epel
#          yum: name=epel-release state=absent
#        - name: Priorities
#          yum: name=yum-plugin-priorities state=latest

