---
- name: Prepare environment for quickstart
  hosts: undercloud
  gather_facts: no
  tasks:
    - name: Here comes any setup which is required for quickstart to run
      debug: msg="Here comes any setup which is required for quickstart to run"
